### ISSUE TITLE
Failed to start example.js

### ISSUE THREAD

**Issue by jngd** [Geode-solutions/genepi-template#11]
I'm trying to run example.js but I'm getting this output:

```
➜  example-napi git:(master) npm run example

> @geode/genepi-template@0.0.0-semantically-released example /Users/jngd/dev/example-napi
> node ./example.js

/Users/jngd/dev/example-napi/node_modules/bindings/bindings.js:135
  throw err;
  ^

Error: Could not locate the bindings file. Tried:
 → /Users/jngd/dev/example-napi/build/genepi_template.node
 → /Users/jngd/dev/example-napi/build/Debug/genepi_template.node
 → /Users/jngd/dev/example-napi/build/Release/genepi_template.node
 → /Users/jngd/dev/example-napi/out/Debug/genepi_template.node
 → /Users/jngd/dev/example-napi/Debug/genepi_template.node
 → /Users/jngd/dev/example-napi/out/Release/genepi_template.node
 → /Users/jngd/dev/example-napi/Release/genepi_template.node
 → /Users/jngd/dev/example-napi/build/default/genepi_template.node
 → /Users/jngd/dev/example-napi/compiled/14.17.6/darwin/x64/genepi_template.node
 → /Users/jngd/dev/example-napi/addon-build/release/install-root/genepi_template.node
 → /Users/jngd/dev/example-napi/addon-build/debug/install-root/genepi_template.node
 → /Users/jngd/dev/example-napi/addon-build/default/install-root/genepi_template.node
 → /Users/jngd/dev/example-napi/lib/binding/node-v83-darwin-x64/genepi_template.node
    at bindings (/Users/jngd/dev/example-napi/node_modules/bindings/bindings.js:126:9)
    at Object.<anonymous> (/Users/jngd/dev/example-napi/example.js:24:34)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
    at internal/main/run_main_module.js:17:47 {
  tries: [
    '/Users/jngd/dev/example-napi/build/genepi_template.node',
    '/Users/jngd/dev/example-napi/build/Debug/genepi_template.node',
    '/Users/jngd/dev/example-napi/build/Release/genepi_template.node',
    '/Users/jngd/dev/example-napi/out/Debug/genepi_template.node',
    '/Users/jngd/dev/example-napi/Debug/genepi_template.node',
    '/Users/jngd/dev/example-napi/out/Release/genepi_template.node',
    '/Users/jngd/dev/example-napi/Release/genepi_template.node',
    '/Users/jngd/dev/example-napi/build/default/genepi_template.node',
    '/Users/jngd/dev/example-napi/compiled/14.17.6/darwin/x64/genepi_template.node',
    '/Users/jngd/dev/example-napi/addon-build/release/install-root/genepi_template.node',
    '/Users/jngd/dev/example-napi/addon-build/debug/install-root/genepi_template.node',
    '/Users/jngd/dev/example-napi/addon-build/default/install-root/genepi_template.node',
    '/Users/jngd/dev/example-napi/lib/binding/node-v83-darwin-x64/genepi_template.node'
  ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @geode/genepi-template@0.0.0-semantically-released example: `node ./example.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @geode/genepi-template@0.0.0-semantically-released example script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/jngd/.npm/_logs/2021-09-23T17_34_08_425Z-debug.log
```

**Environment:**

node v14.17.6
npm 6.14.15

Tried to remove node_modules folder but no luck until now.

Any idea?

**Comment by jngd** [comment]
Issue on my env.
